### ISSUE TITLE
Can you support swift3?

### ISSUE THREAD

**Issue by DarielChen** [PacktPublishing/swift-3-fp#1]

**Comment by ghost** [comment]
Hi @DarielChen, thank you for contacting us. Yes, all the code are compatible with Swift 3.

**Comment by DarielChen** [comment]
But I can not run the project on Xcode8.

**Comment by ghost** [comment]
Yes, that is the last chapter which currently won't run on Xcode 8. We are working on it and will soon be updating the code. Let us know if there are further concerns.

**Comment by conqueror** [comment]
@DarielChen Hi, I have updated first 4 chapters and chapter 11 for the Xcode 8.2.1 Swift 3.0.2: https://github.com/PacktPublishing/Swift-3-Functional-Programming/tree/SecondEdition.

**Comment by DarielChen** [comment]
Thanks
