### ISSUE TITLE
errors attempting to extract zip archive to mac

### ISSUE THREAD

**Issue by dkliman** [PacktPublishing/swift-3-fp#3]
here are some error messages I've encountered, attempting to extract the zip archive of this repository...

when I tried to open with Archive Utility, I got:

<img width="378" alt="00000024" src="https://cloud.githubusercontent.com/assets/672232/23589526/558e9b6c-0201-11e7-888c-8db71534029d.png">

when I tried with a The Unarchiver I got:

<img width="458" alt="00000025" src="https://cloud.githubusercontent.com/assets/672232/23589540/882509b2-0201-11e7-9d70-8497d334e3fa.png">

**Comment by conqueror** [comment]
Hi Dave,
Thanks for buying/reading the book and sorry for the inconvenience.
Team at Packt Publishing will fix the issue soon.
In the meantime, could you please use our GitHub repo for the book?
https://github.com/PacktPublishing/Swift-3-Functional-Programming

GitHub repo is up to date for Swift 3.0.2.

Thanks,
Fatih Nayebi, Ph.D.
Director, Consulting @ CGI | Postdoctoral Researcher @ ETS
+ 1 (514) 358-2313 - LinkedIn

**Comment by dkliman** [comment]
I believe the problem was with the very GitHub repo you mentioned above, which is this one?

<img width="410" alt="00000026" src="https://cloud.githubusercontent.com/assets/672232/23596684/6aeac7f2-025f-11e7-9b9a-eaef396f769c.png">

I looked at the repo and for the chapter 1 playground it looks like there are a lot of pieces to deal with if i don't simply download the zip... it's difficult to gather all the disparate pieces to make a working whole, it looks like.

**Comment by dkliman** [comment]
I would like to mention, that `git clone https://github.com/PacktPublishing/Swift-3-Functional-Programming.git ` worked just fine, at least. :-). UPDATE: I stand corrected. although it seemed to download between 1500 and 2000 files or so, without errors, I get numerous warnings in Xcode about missing files.

<img width="1303" alt="00000027" src="https://cloud.githubusercontent.com/assets/672232/23606026/9429c726-0291-11e7-9f0a-28249a47a3dc.png">
